/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContUsuario;
import Logica.dtColaborador;
import Logica.dtFecha;
import Logica.dtProponente;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author juan
 */
public class Alta_perfil extends javax.swing.JFrame {
// variables y cosas generales;

    ContUsuario contUsu = ContUsuario.getInstance();
    boolean usuTipo;
    String imagenRuta = "COSO";
    JFileChooser navegadorArchivos = new JFileChooser();

    /**
     * Creates new form Alta_perfil
     */
    public Alta_perfil() {
        initComponents();
        String imagenRuta = null;
        JFileChooser navegadorArchivos = new JFileChooser();
        jT_direccion.enable(false);
        jT_web.enable(false);
        jtp_biografia.enable(false);
        jb_aceptar.setEnabled(false);
        this.setLocationRelativeTo(null);
        Date min = new Date("1950/01/01");
        Date max = new Date("2000/12/31");
        jdc_fechaNac.getDateEditor().setEnabled(false);
        jdc_fechaNac.setMaxSelectableDate(max);
        jdc_fechaNac.setMinSelectableDate(min);
        jP_contra.setText(null);
        jP_contraVS.setText(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jL_imagenP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jb_examinar = new javax.swing.JButton();
        jrb_proponente = new javax.swing.JRadioButton();
        jrb_colaborador = new javax.swing.JRadioButton();
        jb_aceptar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jT_nick = new javax.swing.JTextField();
        jT_nombre = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jT_email = new javax.swing.JTextField();
        jdc_fechaNac = new com.toedter.calendar.JDateChooser();
        jT_web = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtp_biografia = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jP_contra = new javax.swing.JPasswordField();
        jP_contraVS = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 20, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 20, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 77;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.ipady = 121;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 0, 0);
        jPanel1.add(jL_imagenP, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 20, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jb_examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_examinarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 20, 0, 0);
        jPanel1.add(jb_examinar, gridBagConstraints);

        jrb_proponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_proponenteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 8, 0, 0);
        jPanel1.add(jrb_proponente, gridBagConstraints);

        jrb_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_colaboradorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 20, 0, 0);
        jPanel1.add(jrb_colaborador, gridBagConstraints);

        jb_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 49, 0);
        jPanel1.add(jb_aceptar, gridBagConstraints);

        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 8, 49, 0);
        jPanel1.add(jb_cancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 90;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 27, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 0, 0);
        jPanel1.add(jT_nick, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 0);
        jPanel1.add(jT_nombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 0);
        jPanel1.add(jT_apellido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 76;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 0, 0);
        jPanel1.add(jT_email, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 61;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 18, 0, 0);
        jPanel1.add(jdc_fechaNac, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 92;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 21, 0, 79);
        jPanel1.add(jT_web, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 90;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 27, 0, 0);
        jPanel1.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 92;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 21, 0, 79);
        jPanel1.add(jT_direccion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 90;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 32, 0, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        jScrollPane1.setViewportView(jtp_biografia);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 90;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.ipady = 327;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 32, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 37;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 50, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 20, 0, 0);
        jPanel1.add(jP_contra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPanel1.add(jP_contraVS, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        limpiarTxt();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jrb_colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_colaboradorActionPerformed
        usuTipo = false;
        jb_aceptar.setEnabled(true);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jrb_proponente.setSelected(false);
        jT_web.setText("");
        jT_direccion.setText("");
        jtp_biografia.setText("");

    }//GEN-LAST:event_jrb_colaboradorActionPerformed

    private void jrb_proponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_proponenteActionPerformed
        jrb_colaborador.setSelected(false);
        usuTipo = true;
        jb_aceptar.setEnabled(true);
        jT_direccion.enable();
        jT_web.enable();
        jtp_biografia.enable();
        jrb_colaborador.setSelected(false);
    }//GEN-LAST:event_jrb_proponenteActionPerformed

    private void jb_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aceptarActionPerformed
        if (altaPerfil() == true) {
            JOptionPane.showMessageDialog(null, "Usuario agregado con exito");
            limpiarTxt();
        } else {
            // JOptionPane.showMessageDialog(null, "No se pudo agregar el usuario");
        }
    }//GEN-LAST:event_jb_aceptarActionPerformed

    private void jb_examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_examinarActionPerformed
        selecImagen();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_examinarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_imagenP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jP_contra;
    private javax.swing.JPasswordField jP_contraVS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_direccion;
    private javax.swing.JTextField jT_email;
    private javax.swing.JTextField jT_nick;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jT_web;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jb_aceptar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_examinar;
    private com.toedter.calendar.JDateChooser jdc_fechaNac;
    private javax.swing.JRadioButton jrb_colaborador;
    private javax.swing.JRadioButton jrb_proponente;
    private javax.swing.JTextArea jtp_biografia;
    // End of variables declaration//GEN-END:variables

// funciones
    private boolean controlDatos() throws Exception {
        
        if (jT_nick.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nickname vacio");
            jT_nick.selectAll();
            jT_nick.requestFocus();
            return false;
        }
        if (contUsu.existeUsuario(jT_nick.getText())) {
            JOptionPane.showMessageDialog(null, "Ya existe un otro usuario con este nickname");
            jT_nick.selectAll();
            jT_nick.requestFocus();
            return false;
        }
        if (jP_contra.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña");
            jP_contra.selectAll();
            jP_contra.requestFocus();
            return false;
        }
        if (jP_contraVS.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la confirmacion de la contraseña");
            jP_contraVS.selectAll();
            jP_contraVS.requestFocus();
            return false;
        }
        
        if (jP_contra.getText().equals(jP_contraVS.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Contraseñas diferentes!");
            jP_contra.selectAll();
            jP_contra.requestFocus();
            return false;
        }
        if (jT_nombre.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nombre vacio");
            jT_nombre.selectAll();
            jT_nombre.requestFocus();
            return false;
        }
        if (jT_apellido.getText() == null) {
            JOptionPane.showMessageDialog(null, "Apellido vacio");
            jT_apellido.selectAll();
            jT_apellido.requestFocus();
            return false;
        }
        if (jT_email.getText() == null) {
            JOptionPane.showMessageDialog(null, "Email vacio");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (compruebaEmail(jT_email.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Email incorrecto");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (contUsu.existeMail(jT_email.getText())) {
            JOptionPane.showMessageDialog(null, "Ya existe otro usuario registrado con este mail");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (jdc_fechaNac == null) {
            JOptionPane.showMessageDialog(null, "Fecha nacimiento vacia");
            jdc_fechaNac.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean fechaok() {
        int dia = 0, mes = 0, anio = 0;
        dia = jdc_fechaNac.getDate().getDay();
        mes = jdc_fechaNac.getDate().getMonth();
        anio = jdc_fechaNac.getDate().getYear();
        
        int Cdia = 01, cMes = 01, Canio = 1945;
        if (dia == Cdia) {
            if (mes == cMes) {
                if (anio == Canio) {
                    return true;
                }
            }
        }
        return false;
    }
    
    private dtFecha getFechajdc() {
        dtFecha fecha;
        fecha = new dtFecha(Integer.toString(jdc_fechaNac.getDate().getDay()), Integer.toString(jdc_fechaNac.getDate().getMonth()), Integer.toString(jdc_fechaNac.getDate().getYear()));
        return fecha;
    }
    
    private boolean compruebaEmail(String email) {
        // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        
        return mather.find();
    }
    
    private void limpiarTxt() {
        jT_nick.setText(null);
        jT_nombre.setText(null);
        jT_apellido.setText(null);
        jT_email.setText(null);
        jdc_fechaNac.setCalendar(null);
        jT_direccion.setText(null);
        jT_web.setText(null);
        jtp_biografia.setText(null);
        jrb_colaborador.setSelected(false);
        jrb_proponente.setSelected(false);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jb_aceptar.disable();
        jL_imagenP.setIcon(null);
        jP_contra.setText(null);
        jP_contraVS.setText(null);
        jb_aceptar.setEnabled(false);
    }
    
    private boolean altaPerfil() {
        
        try {
            
            if (controlDatos() == true) {
                
                if (usuTipo == false) {
                    
                    dtColaborador dtCola = new dtColaborador((jT_nombre.getText()), jT_apellido.getText(), jT_nick.getText(),
                            imagenRuta, jT_email.getText(), getFechajdc(), jP_contra.getText());
                    contUsu.agregarUsu(dtCola);
                    return true;
                }
                
                if (usuTipo == true) {
                    dtProponente dtprop = new dtProponente(jT_nombre.getText(), jT_apellido.getText(), jT_nick.getText(), imagenRuta, jT_email.getText(), getFechajdc(), jT_direccion.getText(), jtp_biografia.getText(), jT_web.getText(), jP_contra.getText());
                    contUsu.agregarUsu(dtprop);
                    return true;
                }
                
            } else {
                return false;
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        return false;
        
    }
    
    private void selecImagen() {
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        navegadorArchivos.setFileFilter(filtroImagen);
        navegadorArchivos.showOpenDialog(this);
        File imagen = navegadorArchivos.getSelectedFile();
        String path = navegadorArchivos.getSelectedFile().getPath();
        jL_imagenP.setIcon(new ImageIcon(path));
        ImageIcon icon = new ImageIcon(path);
        Image foto = icon.getImage();
        Image nuevaFoto = foto.getScaledInstance(jL_imagenP.getWidth(), jL_imagenP.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon nuevoIcono = new ImageIcon(nuevaFoto);
        jL_imagenP.setIcon(nuevoIcono);
        //BufferedImage img= nuevoIcono;
        salvarImagen(foto);
    }
    
    private void salvarImagen(Image imagen) {
        BufferedImage img = (BufferedImage) imagen;
        File outputfile = new File("/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPerfil" + jT_nick.getText() + ".png");
        imagenRuta = "/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPerfil" + jT_nick.getText() + ".png";
        try {
            ImageIO.write(img, "png", outputfile);
        } catch (IOException ex) {
            Logger.getLogger(Alta_perfil.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }
}
