/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContColaboracion;
import Logica.ContPropuesta;
import Logica.ContUsuario;
import Logica.culturarteFabrica;
import Logica.dtColProp;
import Logica.dtCola;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Cancelar_colaboracion_a_Propuesta extends javax.swing.JInternalFrame {
private culturarteFabrica CF = culturarteFabrica.getInstance();
    private ContUsuario ICU = ContUsuario.getInstance();
    private ContColaboracion ICC= ContColaboracion.getInstance();    
private ContPropuesta contP=ContPropuesta.getInstance();
    /**
     * Creates new form Cancelar_colaboracion_a_Propuesta
     */
    public Cancelar_colaboracion_a_Propuesta() {
        initComponents();
        contP.propAutomaticas();
        this.setSize(775, 567);
        
        jLabel1.setText("Colaboradores");
        jLabel2.setText("Colaboracion seleccionada:");
        jLabel3.setText("Titulo");
        jLabel4.setText("Nickname");
        labeltitulo.setText("Seleccione una colaboracion");
        labelnickname.setText("Seleccione una colaboracion");
        btncancelar.setText("Cancelar");
        btnconfirmar.setText("Eliminar");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablacolaboradores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacolaboracion = new javax.swing.JTable();
        btnconfirmar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacolaboraciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        labelnickname = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        tablacolaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ));
        tablacolaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacolaboradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacolaboradores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(35, 87, 121, 421);

        jLabel1.setText("Colaboradores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(35, 28, 105, 15);

        tablacolaboracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Fecha", "Hora", "Monto", "Retorno"
            }
        ));
        jScrollPane2.setViewportView(tablacolaboracion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(176, 351, 577, 183);

        btnconfirmar.setText("Eliminar");
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconfirmar);
        btnconfirmar.setBounds(605, 260, 90, 25);

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar);
        btncancelar.setBounds(497, 260, 96, 25);

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(30, 59, 123, 19);

        tablacolaboraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Titulo", "Nickname"
            }
        ));
        tablacolaboraciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacolaboracionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablacolaboraciones);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(176, 59, 291, 272);

        jLabel2.setText("Colaboracion seleccionada:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(487, 59, 195, 15);

        jLabel3.setText("Titulo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(487, 82, 40, 15);

        jLabel4.setText("Nickname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(487, 111, 68, 15);

        labeltitulo.setText("Seleccione una colaboracion");
        getContentPane().add(labeltitulo);
        labeltitulo.setBounds(540, 82, 202, 15);

        labelnickname.setText("Seleccione una colaboracion");
        getContentPane().add(labelnickname);
        labelnickname.setBounds(562, 111, 202, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
        List<String> colaboradores= ICU.listarColaboradoresporNick(txtbuscar.getText());
        DefaultTableModel modelo=(DefaultTableModel) tablacolaboradores.getModel();
        modelo.setRowCount(0);
        for (int i=0;i<colaboradores.size();i++) {
            String c=colaboradores.get(i);
            Object[] dat={c};
            modelo.addRow(dat);
        }
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void tablacolaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacolaboradoresMouseClicked
        // TODO add your handling code here:
        vaciarTablas();
        int row=tablacolaboradores.rowAtPoint(evt.getPoint());
        int col=tablacolaboradores.columnAtPoint(evt.getPoint());
        
        DefaultTableModel modelo=(DefaultTableModel) tablacolaboraciones.getModel();
        modelo.setRowCount(0);
        List<dtCola> list=ICC.listarcolaboracionesdelcolaborador((String)tablacolaboradores.getValueAt(row, col));
        labelnickname.setText((String)tablacolaboradores.getValueAt(row, col));
        Iterator it=list.iterator();
        while(it.hasNext()){
            dtCola dtco=(dtCola) it.next();
            Object[] dat={dtco.getTitulo(),(String)tablacolaboradores.getValueAt(row, col)};
            modelo.addRow(dat);
        }
    }//GEN-LAST:event_tablacolaboradoresMouseClicked

    private void tablacolaboracionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacolaboracionesMouseClicked
        // TODO add your handling code here:
        int row=tablacolaboraciones.rowAtPoint(evt.getPoint());
        int col=tablacolaboraciones.columnAtPoint(evt.getPoint());        
        DefaultTableModel modelo=(DefaultTableModel) tablacolaboracion.getModel();
        modelo.setRowCount(0);
        
        labeltitulo.setText((String)tablacolaboraciones.getValueAt(row, col));
        dtColProp dtcp=ICC.seleccionarColaboracion(labelnickname.getText(),(String)tablacolaboraciones.getValueAt(row, col));       
        
            Object[] dat={(String)tablacolaboraciones.getValueAt(row, col),dtcp.getFechaCol().getFecha(),dtcp.getHoraCol().getHora(),dtcp.getMontoColaborado(),dtcp.getRetorno()};
            modelo.addRow(dat);  
    }//GEN-LAST:event_tablacolaboracionesMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
        try {
        if(labelnickname.getText().isEmpty() || labeltitulo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Seleccione una propuesta");}
        if(!labelnickname.getText().isEmpty() && !labeltitulo.getText().isEmpty()){ 
            ICC.eliminarcolaboracion(labelnickname.getText(), labeltitulo.getText());
                JOptionPane.showMessageDialog(null,"Colaboracion eliminada"); 
                limpiartodo();}
            
         } catch (Exception ex) {
                Logger.getLogger(Cancelar_colaboracion_a_Propuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnconfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelnickname;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JTable tablacolaboracion;
    private javax.swing.JTable tablacolaboraciones;
    private javax.swing.JTable tablacolaboradores;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    public void vaciarTablas(){
        DefaultTableModel modelo=(DefaultTableModel) tablacolaboracion.getModel();
        modelo.setRowCount(0);
        
        DefaultTableModel modelo2=(DefaultTableModel) tablacolaboraciones.getModel();
        modelo2.setRowCount(0);        
}

    private void limpiartodo() {
        labeltitulo.setText("Seleccione una colaboracion");
        labelnickname.setText("Seleccione una colaboracion");  
        vaciarTablas();
    }

}
