/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContColaboracion;
import Logica.ContUsuario;
import Logica.dtCola;
import Logica.dtColaborador;
import Logica.dtUsuario;
import java.awt.Color;
import java.awt.Image;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Consulta_de_Perfil_de_Colaborador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta_de_Perfil_de_Colaborador
     */
    
    private ContUsuario ICU = ContUsuario.getInstance();
    private ContColaboracion ICC= ContColaboracion.getInstance();
    
    public Consulta_de_Perfil_de_Colaborador() {
        initComponents();
        jLabel1.setText("Colaboradores");
        jLabel2.setText("Informacion para:");
        labelnickname.setText("Seleccione un colaborador...");
        jLabel3.setText("Imagen:");
        jLabel4.setText("Colaboraciones:");
        jButton1.setText("Cancelar");
        this.setSize(655, 596);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablecolaborador = new javax.swing.JTable();
        labelnickname = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablepropuestas1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelimagen = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(37, 73, 125, 425);

        jLabel1.setText("Colaboradores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(54, 23, 105, 15);

        jLabel2.setText("Informacion para:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(194, 23, 125, 15);

        tablecolaborador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Email", "Nacimiento"
            }
        ));
        jScrollPane2.setViewportView(tablecolaborador);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(194, 44, 414, 81);

        labelnickname.setText("Seleccione un colaborador...");
        getContentPane().add(labelnickname);
        labelnickname.setBounds(337, 23, 203, 15);

        tablepropuestas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Estado", "Proponente", "Monto recaudado"
            }
        ));
        jScrollPane4.setViewportView(tablepropuestas1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(194, 295, 414, 203);

        jLabel4.setText("Colaboraciones:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(194, 276, 115, 15);

        jLabel3.setText("Imagen:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 137, 57, 15);
        getContentPane().add(labelimagen);
        labelimagen.setBounds(194, 158, 100, 100);

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });
        getContentPane().add(txtbuscar);
        txtbuscar.setBounds(37, 44, 118, 19);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(511, 504, 96, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
        List<String> colaboradores= ICU.listarColaboradoresporNick(txtbuscar.getText());
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (int i=0;i<colaboradores.size();i++) {
            String c=colaboradores.get(i);
            Object[] dat={c};
            modelo.addRow(dat);
        }

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        vaciarTablas();
        int row=jTable1.rowAtPoint(evt.getPoint());
        int col=jTable1.columnAtPoint(evt.getPoint());
        dtColaborador dtc=(dtColaborador)ICU.infoColaborador((String)jTable1.getValueAt(row, col));
        DefaultTableModel modelo=(DefaultTableModel) tablecolaborador.getModel();
        modelo.setRowCount(0);
        Object[] dat={dtc.getNombre(),dtc.getApellido(),dtc.getEmail(),dtc.getFechaNac().getFecha()};
        labelnickname.setText(dtc.getNickname()); //dtc.getNickname()
        modelo.addRow(dat);
        labelimagen.setIcon(new ImageIcon(dtc.getImagen()));
       ImageIcon icon = new ImageIcon(dtc.getImagen());
       Image foto = icon.getImage();
       Image nuevaFoto = foto.getScaledInstance(labelimagen.getWidth(), labelimagen.getHeight(), Image.SCALE_DEFAULT);
       ImageIcon nuevoIcono = new ImageIcon(nuevaFoto);
       labelimagen.setIcon(nuevoIcono);
        
        DefaultTableModel modelo2=(DefaultTableModel) tablepropuestas1.getModel();
        modelo2.setRowCount(0);
        List<dtCola> list=ICC.listarcolaboracionesdelcolaborador((String)jTable1.getValueAt(row, col));
        Iterator it=list.iterator();
        while(it.hasNext()){
            dtCola dtco=(dtCola) it.next();
            Object[] dat2={dtco.getTitulo(),dtco.getEstado(),dtco.getProponente(),dtco.getMonto_recaudado()};
            modelo2.addRow(dat2);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        labelimagen.setText("");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelimagen;
    private javax.swing.JLabel labelnickname;
    private javax.swing.JTable tablecolaborador;
    private javax.swing.JTable tablepropuestas1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
public void vaciarTablas(){
    DefaultTableModel modelo=(DefaultTableModel) tablepropuestas1.getModel();
    modelo.setRowCount(0);    
}

}
