/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContPropuesta;
import Logica.ContUsuario;
import Logica.dtContieneArray;
import Logica.DtPropuesta;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Consulta_de_Propuesta_por_Estado extends javax.swing.JInternalFrame {

    ContUsuario contUsu = ContUsuario.getInstance();
    ContPropuesta contProp = ContPropuesta.getInstance();
    ArrayList<dtContieneArray> arregloContiene = new ArrayList<>();
    ArrayList<DtPropuesta> contienProp = new ArrayList<>();
    Vector datos = new Vector();

    /**
     * Creates new form Consulta_de_Propuesta_por_Estado
     */
    public Consulta_de_Propuesta_por_Estado() {
        initComponents();
        contProp.propAutomaticas();
        cargaEstados();
        this.setSize(844, 580);
        jLabel1.setText("Estados");
        jLabel6.setText("Propuestas en estado");
        jLabel2.setText("Imagen");
        lableEstadk.setText("Estado");
        txtmontotoal.setEditable(false);
        jLabel5.setText("Monto total");
        jLabel4.setText("Colaboradores");
        jButton1.setText("Cancelar");
        datos.add("Titulo");
        datos.add("Descripcion");
        datos.add("Lugar");
        datos.add("Fecha");
        datos.add("Precio Entrada");
        datos.add("Monto requerido");
        txtmontotoal.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepropuesta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lableEstadk = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacolaboradores = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtmontotoal = new javax.swing.JTextField();
        txtimagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableestados = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxt_buscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        tablepropuesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripcion", "Lugar", "Fecha", "Precio entrada", "Monto requerido"
            }
        ));
        tablepropuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepropuestaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablepropuesta);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 787;
        gridBagConstraints.ipady = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 0);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        getContentPane().add(lableEstadk, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        tablacolaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ));
        jScrollPane3.setViewportView(tablacolaboradores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 141;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 0);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 0);
        getContentPane().add(txtmontotoal, gridBagConstraints);

        txtimagen.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 158;
        gridBagConstraints.ipady = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 11, 0, 0);
        getContentPane().add(txtimagen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 60, 15, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        tableestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        tableestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableestadosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableestados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 0);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 227;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 30, 0, 0);
        getContentPane().add(jScrollPane5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jtxt_buscar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableestadosMouseClicked
        // TODO add your handling code here:
        int row = tableestados.rowAtPoint(evt.getPoint());
        int col = tableestados.columnAtPoint(evt.getPoint());
        System.out.println("fila" + row);
        System.out.println("columna" + col);
        llenaGrillaPorEstado((String) tableestados.getValueAt(row, 0));
        txtmontotoal.setText("0");
        lableEstadk.setText((String) tableestados.getValueAt(row, 0));

    }//GEN-LAST:event_tableestadosMouseClicked

    private void tablepropuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepropuestaMouseClicked
        int row = tablepropuesta.rowAtPoint(evt.getPoint());
        int col = tablepropuesta.columnAtPoint(evt.getPoint());
        cargaColaboradores((String) tablepropuesta.getValueAt(row, 0));
        cargaMonto((String) tablepropuesta.getValueAt(row, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_tablepropuestaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxt_buscar;
    private javax.swing.JLabel lableEstadk;
    private javax.swing.JTable tablacolaboradores;
    private javax.swing.JTable tableestados;
    private javax.swing.JTable tablepropuesta;
    private javax.swing.JLabel txtimagen;
    private javax.swing.JTextField txtmontotoal;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * funcion que recibe un vector con el nombre de la cabecera un arreglo de
     * string y un jtable
     */
    private void llegaGrillaString(Vector v, ArrayList<String> e, JTable jt) {
        DefaultTableModel modelo;

        modelo = new DefaultTableModel(v, e.size());
        for (int i = 0; i < e.size(); i++) {
            String es = (String) e.get(i);
            modelo.setValueAt(es, i, 0);
            //modelo.setValueAt(p.getNickproponente(), i, 1);
        }
        jt.setModel(modelo);
    }

    private void cargaEstados() {
        ArrayList<String> estado = (ArrayList<String>) contProp.getEstadosString();
        estado.remove("Desactivada");
        Vector v = new Vector();
        v.add("Estado");
        llegaGrillaString(v, estado, tableestados);
        arregloContiene = (ArrayList<dtContieneArray>) crearArreglos(estado);
    }

    private ArrayList<dtContieneArray> crearArreglos(ArrayList<String> estado) {
        ArrayList<dtContieneArray> nuevoArreglo = new ArrayList<>();
        for (int i = 0; i < estado.size(); i++) {
            nuevoArreglo.add((dtContieneArray) getArrayProp((String) estado.get(i)));
        }
        return nuevoArreglo;
    }

    private dtContieneArray getArrayProp(String estado) {

        dtContieneArray contiene = new dtContieneArray((ArrayList<DtPropuesta>) contProp.getPropuestasxEstado(estado), estado);

        return contiene;
    }

    private void llenaGrillaPorEstado(String estado) {
        DefaultTableModel modelo = null;
        int cont = 0;
        for (int i = 0; i < arregloContiene.size(); i++) {
            dtContieneArray dtcA = arregloContiene.get(i);
            if (dtcA.getNombreArray().equals(estado)) {
                modelo = new DefaultTableModel(datos, dtcA.getMyArreglo().size());
                armarModelo(modelo, dtcA);
            }
        }

        tablepropuesta.setModel(modelo);
        DefaultTableModel model = (DefaultTableModel) tablacolaboradores.getModel();
        model.setRowCount(0);
        tablacolaboradores.setModel(model);
    }

    private void armarModelo(DefaultTableModel modelo, dtContieneArray dtC) {
        ArrayList<DtPropuesta> arregloProp = (ArrayList<DtPropuesta>) dtC.getMyArreglo();
        DtPropuesta prop;
        for (int i = 0; i < arregloProp.size(); i++) {
            prop = (DtPropuesta) arregloProp.get(i);
            modelo.setValueAt(prop.getTitulo(), i, 0);
            modelo.setValueAt(prop.getDescripcion(), i, 1);
            modelo.setValueAt(prop.getLugar(), i, 2);
            modelo.setValueAt(prop.getFechaRealizacion().getFecha(), i, 3);
            modelo.setValueAt(prop.getPrecioentrada(), i, 4);
            modelo.setValueAt(prop.getMontorequerido(), i, 5);

        }
    }

    private void cargaColaboradores(String propTitulo) {
        ArrayList<String> cola = null;
        cola = (ArrayList<String>) contProp.getColaboradoresString(propTitulo);
        llenaGrillaCola(cola);
    }

    private void llenaGrillaCola(ArrayList<String> cola) {
        Vector v = new Vector();
        v.add("Colaboradores");
        DefaultTableModel modelo = new DefaultTableModel(v, cola.size());
        for (int i = 0; i < cola.size(); i++) {
            modelo.setValueAt((String) cola.get(i), i, 0);
        }
        tablacolaboradores.setModel(modelo);
    }

    private void cargaMonto(String p) {
        int m = (Integer) contUsu.getMontoColaborado(p);
        txtmontotoal.setText(Integer.toString(m));
    }
}
